num_classes: 527
sample_rate: 32000
loader:
  _target_: target_distillation.data.loader.LogitsDataloader
  database:
    _target_: target_distillation.data.audioset.AudiosetLogitsWdsDataset
    json_path: ${system.db_root}/relabeling/audioset_full/database.json
    balance_classes: false
    cache: false
    clip_length: 10.0
    sample_rate: ${db.sample_rate}
    dataset_path: ${system.db_root}/wds/audioset_32khz
  batch_size: ${loader.batch_size}
  num_workers: ${loader.num_workers}
  seed: 0
  augmentation: null
  mixup: null