num_classes: 527
sample_rate: 32000
num_train_samples: 1833973
loader:
  _target_: target_distillation.data.loader.LogitsDataloader
  database:
    _target_: target_distillation.data.audioset.AudiosetLogitsDataset
    audio_reader:
      _target_: target_distillation.data.audioset.AudioReaderSD
      database_path: ${system.db_root}/audioset_32khz_flac_sd
      clip_length: 5.0
      sample_rate: ${db.sample_rate}
    json_path: ${system.db_root}/relabeling/domain_classifier3/database.json
    balance_classes: false
    cache: false
  batch_size: ${loader.batch_size}
  num_workers: ${loader.num_workers}
  seed: 0
  augmentation: 
    _target_: target_distillation.data.utils.Augmentation
    gain_augment: 0
    roll_axis: 1
    shift: null
    shift_range: 10000
  mixup:
    _target_: target_distillation.data.utils.Mixup
    mix_interval: 2.0
    mix_beta: 2.0
