num_classes: 12
sample_rate: 32000
num_train_samples: 16000
loader:
  _target_: target_distillation.data.loader.LogitsDataloader
  database:
    _target_: target_distillation.data.speech_commands.SpeechCommandsDataset
    root_path: ${system.db_root}/speech_commands-v0.0.2-5h
    validation_set: valid
    train_set: train
  batch_size: ${loader.batch_size}
  num_workers: ${loader.num_workers}
  seed: 0
  augmentation:
    _target_: target_distillation.data.utils.Augmentation
    gain_augment: 0
    roll_axis: 1
    shift: null
    shift_range: 12800
    mixstyle_p: 0  # 0.3
    mixstyle_alpha: 0  # 0.4
  mixup:
    null