num_classes: 10
sample_rate: 32000
num_train_samples: 139620
loader:
  _target_: target_distillation.data.loader.LogitsDataloader
  database:
    _target_: target_distillation.data.tau2022.Tau2022LogitsDataset
    logit_file: ${system.db_root}/logits/tau2022_ensemble_logits/database.json
    root_path: ${system.db_root}/tau2022_32khz_sd
    validation_set: test
    train_set: train_100
    cache: true
  batch_size: ${loader.batch_size}
  num_workers: ${loader.num_workers}
  seed: 0
  augmentation:
    _target_: target_distillation.data.utils.Augmentation
    gain_augment: 0
    roll_axis: 1
    shift: null
    shift_range: 3200
    mixstyle_p: 0  # 0.3
    mixstyle_alpha: 0  # 0.4
  