_target_: torch.nn.Sequential
_args_:
  - _target_: torch.nn.Conv2d
    in_channels: 104
    out_channels: 527
    kernel_size: 
      - 1
      - 1
    stride:
      - 1
      - 1
    padding: 0
    bias: false
  - _target_: torch.nn.BatchNorm2d
    num_features: 527
  - _target_: torch.nn.AdaptiveAvgPool2d
    output_size:
      - 1
      - 1