_target_: target_distillation.model_wrapper.ModelWrapper
model:
  _target_: dcase2024_task1_baseline.models.baseline.get_model
  n_classes: ${db.num_classes}
  in_channels: 1
  base_channels: 32
  channels_multiplier: 1.8
  expansion_rate: 2.1
  add_feats: true