_target_: target_distillation.model_wrapper.ModelWrapper
model:
  _target_: dcase2024_task1_baseline.models.gsharp.mobilenet_v1_shared
  num_classes: ${db.num_classes}
  num_basis_kernels: 5
  return_feats: True