defaults:
  - db: audioset_logits_sd
  - system: nt
hydra:
  run:
    dir: ${system.storage_root}/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
loader:
  batch_size: 30
  num_workers: 8
feature_extractor:
  _target_: EfficientAT.models.preprocess.AugmentMelSTFT
  sr: ${db.sample_rate}
  win_length: 800
  hopsize: 320
  n_mels: 128
model:
  _target_: target_distillation.model.LogitDistillationModel
  student:
    _target_: target_distillation.model_wrapper.ModelWrapper
    model:
      _target_: EfficientAT.models.MobileNetV3.get_model
      pretrained_name: mn10_im
      width_mult: 1.0
      num_classes: ${db.num_classes}
  feature_extractor: ${feature_extractor}
  label_loss_prop: 0.1
trainer:
  _target_: padertorch.contrib.aw.trainer.AutocastTrainer
  autocast_enabled: false
  model: ${model}
  optimizer:
    _target_: padertorch.contrib.aw.optimizer.AdamW
    lr: ${lr}
    gradient_clipping: 1.0
    weight_decay: 0.0001
  summary_trigger:
   - 100
   - "iteration"
  checkpoint_trigger:
   - 1000
   - "iteration"
  stop_trigger:
   - "???"
   - "iteration"
  storage_dir: ${hydra:run.dir}
  virtual_minibatch_size: 1
lr: 8e-4
lr_schedule:
  warm_up_len: 0.04
  ramp_down_start: 0.4
  ramp_down_len: 0.475
  last_lr_value: 0.01
epochs: null
num_iterations: 167000
device: 0
experiment_name: target_distillation