defaults:
  - _self_
  - db: tau2022_sd
  - system: nt
hydra:
  run:
    dir: ${system.storage_root}/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
loader:
  batch_size: 30
  num_workers: 0
feature_extractor:
  _target_: EfficientAT.models.preprocess.AugmentMelSTFT
  sr: ${db.sample_rate}
  win_length: 800
  hopsize: 320
  n_mels: 128
model:
  _target_: passt_pt.models.passt.get_ensemble_model
  arch_list:
    - ["passt_s_swa_p16_128_ap476", 10, 10]
    - ["passt_s_swa_p16_128_ap4761", 10, 10]
    - ["passt_s_p16_128_ap472", 10, 10]
    - ["passt_s_p16_s12_128_ap470", 12, 12]
    - ["passt_s_swa_p16_s12_128_ap473", 12, 12]
    - ["passt_s_p16_s14_128_ap469", 14, 14]
    - ["passt_s_swa_p16_s14_128_ap471", 14, 14]
    - ["passt_s_swa_p16_s16_128_ap473", 16, 16]
    - ["passt_s_p16_s16_128_ap468", 16, 16]
repeat: False
experiment_name: target_distillation
segment_length: null
dir_path: /net/vol/werning/db/tau2022_ensemble_logits