defaults:
  - _self_
  - db: tau2022_sd
  - system: nt
  - model: passt_ensemble
  - feature_extractor: passt_ensemble_fe
hydra:
  run:
    dir: ${system.storage_root}/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
loader:
  batch_size: 30
  num_workers: 0
repeat: False
experiment_name: target_distillation
segment_length: null
dir_path: /net/vol/werning/db/tau2022_ensemble_logits