# python ex_finetune.py hydra.run.dir="/net/vol/werning/.../version0/" checkpoint="epoch\=35-step\=164896.ckpt"
# structure: hydra.run.dir/"checkpoints"/checkpoint
# do not forget model: model.net.width_mult=4.0 (pretrained_name?)
defaults:
  - _self_
  - db: tau2022_logits_sd
  - system: nt
  - model: train
hydra:
  run:
    dir: ${system.storage_root}/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
loader:
  batch_size: 64
  num_workers: 2
# feature_extractor:
#   _target_: EfficientAT.models.preprocess.AugmentMelSTFT
#   sr: ${db.sample_rate}
#   win_length: 800
#   hopsize: 320
#   n_mels: 128
#   freqm: 0
#   timem: 0
feature_extractor:
  _target_: target_distillation.feature_extractor.LogMel
  sr: ${db.sample_rate}
  win_length: 3072
  n_fft: 4096
  hopsize: 500
  n_mels: 256
  freqm: 0
  timem: 0
experiment_name: target_distillation_eval
checkpoint: null